global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'usercreation'
    static_configs:
      - targets: ['usercreation:8080']

  # - job_name: 'ordercreation'
  #   static_configs:
  #     - targets: ['ordercreation:8080']
